import requests from './request'
import mockrequest from './mockrequest'
export const reqCategoryList=()=>requests({url:"/product/getBaseCategoryList",method:"get"})
export const reqGetBannerList=()=>mockrequest({url:"/banner",method:"get"})
export const reqFloorList=()=>mockrequest({url:"/floor",method:"get"})
export const reqGetSearchInfo=(params)=>requests({url:"/list",method:"post",data:params})
export const reqGoodInfo=(skuid)=>requests({url:`/item/${skuid}`,method:"get"})
export const addOrUpdataShopCart=(skuId,skuNum)=>requests({url:`/cart/addToCart/${skuId}/${skuNum}`,method:"post"})
export const reqCartList=()=>requests({url:"/cart/cartList",method:"get"})
export const reqDeleteCart=(skuId)=>requests({url:`/cart/deleteCart/${skuId}`,method:"delete"})
export const reqisChecked=(skuId,isChecked)=>requests({url:`/cart/checkCart/${skuId}/${isChecked}`,method:"get"})
export const reqGetCode=(phone)=>requests({url:`/user/passport/sendCode/${phone}`,method:"get"})
export const reqFinishRegister=(data)=>requests({url:`/user/passport/register`,data,method:"post"})
export const reqLogin=(data)=>requests({url:"/user/passport/login",data,method:"post"})
export const reqGetUserInfo=()=>requests({url:"/user/passport/auth/getUserInfo",method:"get"})
export const reqLogOut=()=>requests({url:"/user/passport/logout",method:"get"})
export const reqFindUserAddressList=()=>requests({url:"/user/userAddress/auth/findUserAddressList",method:"get"})
export const reqOrderTrade=()=>requests({url:"/order/auth/trade",method:"get"})
export const reqSubmitOrder=(tradeNo,data)=>requests({url:`/order/auth/submitOrder?tradeNo=${tradeNo}`,data,method:"post"})
export const reqPayMent=(orderId)=>requests({url:`/payment/weixin/createNative/${orderId}`,method:"get"})
export const reqQueryPayStatus=(orderId)=>requests({url:`/payment/weixin/queryPayStatus/${orderId}`,method:"get"})
export const reqOrderList=(page,limit)=>requests({url:`/order/auth/${page}/${limit}`,method:"get"})
 